channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - picard
  - gatk4
  - kraken
  - bwa 
  - samtools
  - ruamel.yaml
  - git
  - pip
  - pip:
      - biopython
      - pytest