name: ecoli food bourne infection workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

    steps:
      # step 1: checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # step 2 use environment.yml dependencies to create conda environment
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: cdiff_pipeline
          python-version: ${{ matrix.python-version }}
      
      # step 3
      - name: Install custom tool
        run: |
          git clone https://github.com/ssi-dk/serum_readfilter
          cd serum_readfilter
          pip install .
          cd ..

       # step 4
      - name: Run test script
        run: |
          conda activate cdiff_pipeline
          make test
      
      # consider adding the webhook to https://github.com/ssi-dk/bifrost_sp_cdiff/